version: '1.0'
services:
  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: ajp
      MYSQL_USER: ajp_n13
      MYSQL_PASSWORD: 12345678
    volumes:
      - db_data:/var/lib/mysql
      - ./db-scripts:/docker-entrypoint-initdb.d

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hocba-n13
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/ajp?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: ajp_n13
      SPRING_DATASOURCE_PASSWORD: 12345678
    depends_on:
      - db
volumes:
  db_data:                         